# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ona"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["kazuyoshi tlacaelel"]
  s.date = "2013-12-14"
  s.description = "Simple shell for deployment."
  s.email = "kazu.dev@gmail.com"
  s.executables = ["ona"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/ona",
    "lib/ona.rb",
    "lib/ona_cli.rb",
    "lib/ona_instructions.rb",
    "lib/ona_server.rb",
    "lib/ona_stack.rb",
    "ona.gemspec",
    "test/helper.rb",
    "test/test_ona.rb"
  ]
  s.homepage = "http://github.com/ktlacaelel/ona"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Ona -- Deployment symplified."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, "= 13.0.1")
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<rake>, "= 13.0.1")
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, "= 13.0.1")
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

